version: 2.1

orbs:
  codecov: codecov/codecov@5.4.3

executors:
  default:
    working_directory: ~/sdk
    docker:
      - image: cimg/node:18.18.0

jobs:
  test:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          key: dependency-cache-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run unit tests with coverage
          command: npm run test:CI
      - codecov/upload:
          token: CODECOV_TOKEN
          slug: trolley/javascript-sdk
          files: coverage/lcov.info
          when: always

  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Integration tests
          command: npm run test
  publish:
    executor: default
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Build distribution
          command: |
            if [[ $CIRCLE_BRANCH = master ]]; then
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              npm run build
              npm publish --access public
            fi
workflows:
  build-test:
    jobs:
      - test:
          context: org-global
          filters:
            tags:
              ignore: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
  publish-deploy:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
