version: 2.1

executors:
  default:
    working_directory: ~/sdk
    docker:
      - image: cimg/node:18.18.0

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Integration tests
          command: npm run test
  publish:
    executor: default
    steps:
      - checkout
      - run:
          name: Build distribution
          command: |
            if [[ $CIRCLE_BRANCH = master ]]; then
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              npm run build
              npm publish --access public
            fi
workflows:
  build-test:
    jobs:
      - build
  publish-deploy:
    jobs:
      - publish:
          filters:
            branches:
              only: master